### PR TITLE
Add support for Python 3.4 and 3.5

### PR DESCRIPTION
**Pull request by eisensheng**
Hi,

this pull request add support for Python 3.4 and 3.5 with the help of six. Tests are also slightly adjusted to run with Python2 and Python3.

The test suite can also be run in multiple environments with the help of Tox now.

Nice lib, btw. :+1:

### CODE REVIEW

**Comment by mvantellingen** [comment]
Nice! If travis is finished I merge it and create a new release right away :+1:

**Comment by eisensheng** [comment]
Thanks for the ultra-fast response! :grinning: Travis failed on 3.5 though. Let me take a look what caused it since it works in tox here.

**Comment by eisensheng** [comment]
Pulling up the version requirements for test dependencies fixed the broken Build. It appears that the problem was solved in <https://github.com/pytest-dev/pytest-django/issues/272>.

**Comment by mvantellingen** [comment]
Ok, thanks!

**Comment by mvantellingen** [comment]
Thanks again, I've just uploaded it to pypi with version 0.4.1 since i forgot to make univeral wheels :-)

**Pull request merged**
