### PR TITLE
Django 3.1 support, dropped support for django 1.1

### PR DESCRIPTION
**Pull request by f213**
Fixed RemovedInDjango40Warning about django.conf.urls.urls()

Dropped support for django 1.11

fixes f213/django#13

### CODE REVIEW

**Comment by f213** [comment]
Hey, @mvantellingen!

I have updated the project to fully support django 3.1. Unfortunately, github checks are not triggered by pull requests, so i need your help to validate this pr.

**Comment by f213** [comment]
Hey @mvantellingen!

Sorry for bothering you again. Any updates on this?

**Review by eduzen — APPROVED** [review]

**Comment by f213** [comment]
Shouldn't we merge it now?

**Comment by mvantellingen** [comment]
Thanks, didn’t see this earlier

**Pull request merged**
